# Generated by Django 3.1.3 on 2020-12-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estuduff_api', '0002_auto_20201122_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplace',
            name='studyProfile',
        ),
        migrations.AddField(
            model_name='studyplace',
            name='studyProfile',
            field=models.ManyToManyField(to='estuduff_api.StudyProfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studyProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estuduff_api.studyprofile'),
        ),
    ]
